pages_build_output_dir = "dist"

# Only Pages-allowed keys in this file
# Environments supported: preview, production (not staging/development)

name = "jetsy-pages"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "jetsy-leads"
database_id = "682478d4-6494-4f47-93e6-be1b6397fe92" 