name = "jetsy-server"
main = "src/server-worker.js"
compatibility_date = "2024-01-01"

[observability.logs]
enabled = true

# No build configuration - this is API only, no React app

[env.production]
name = "jetsy-server-prod"

[env.production.vars]
# CF_ZONE_ID used by the Worker in production
CF_ZONE_ID = "53957945e940cad5e6dd29dd7add1e0c"

[[env.production.d1_databases]]
binding = "DB"
database_name = "jetsy-leads"
database_id = "682478d4-6494-4f47-93e6-be1b6397fe92"

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "jetsy-images-prod"

[env.staging]
name = "jetsy-server-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "jetsy-leads-staging"
database_id = "your-staging-database-id-here"

[[env.staging.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "jetsy-images-staging"

[env.development]
name = "jetsy-server-dev"

[env.development.vars]
# Development environment variables

[[env.development.d1_databases]]
binding = "DB"
database_name = "jetsy-leads"
database_id = "682478d4-6494-4f47-93e6-be1b6397fe92"

[[env.development.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "jetsy-images-dev"

# Add your D1 database
[[d1_databases]]
binding = "DB"
database_name = "jetsy-leads"
database_id = "682478d4-6494-4f47-93e6-be1b6397fe92"

# Add R2 bucket for image storage
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "jetsy-images-prod"
preview_bucket_name = "jetsy-images-dev"
experimental_remote = true

# Environment variables
[vars]
# Add your OpenAI API key as a secret using: wrangler secret put OPENAI_API_KEY --config wrangler.server.toml
# Add your Gemini API key as a secret using: wrangler secret put GEMINI_API_KEY --config wrangler.server.toml
