name = "jetsy-landing"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[observability.logs]
enabled = true

[env.production]
name = "jetsy-landing-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "jetsy-leads"
database_id = "682478d4-6494-4f47-93e6-be1b6397fe92"

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "jetsy-images-prod"

[env.production.vars]
CF_ZONE_ID = "53957945e940cad5e6dd29dd7add1e0c"

