name = "jetsy-landing"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[observability.logs]
enabled = true

# Required secrets (set with: npx wrangler secret put SECRET_NAME)
# - VERCEL_API_TOKEN: Vercel API token for deployment and domain management
# - OPENAI_API_KEY: OpenAI API key for AI features
# - GEMINI_API_KEY: Gemini API key for AI features
# - ADMIN_CHAT_PASSWORD: Password for accessing /chat route

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "jetsy-leads"
database_id = "682478d4-6494-4f47-93e6-be1b6397fe92"

# R2 bucket binding
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "jetsy-images-prod"

# Environment variables
[vars]
CF_ZONE_ID = "53957945e940cad5e6dd29dd7add1e0c"

